# $Dataset$: [Red Wine Quality](https://www.kaggle.com/datasets/uciml/red-wine-quality-cortez-et-al-2009)

Bộ dữ liệu "Red Wine Quality" cung cấp các thông số phân tích của rượu vang từ vùng Vinho Verde ở Bồ Đào Nha (Để biết thêm chi tiết, ta có thể tham khảo ở  Cortez et al., 2009).

Bộ dữ liệu này cung cấp một cái nhìn toàn diện về các yếu tố hóa học có ảnh hưởng đến chất lượng của rượu vang, thông qua các đặc điểm sau:

* Input features:
1. fixed acidity (Độ axit tổng cố định)
2. volatile acidity (Độ axit bay hơi)
3. citric acid 
4. residual sugar (đường dư) 
5. chlorides (clo)
6. free sulfur dioxide (Lưu huỳnh dioxit tự do)
7. total sulfur dioxide (Lưu huỳnh dioxit tổng)
8. density (mật độ)
9. pH
10. sulphates 
11. alcohol (nồng độ cồn)

* Output: Quality score (between 0 -> 10)

## Read data and import library

In [5]:
import pandas as pd
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import seaborn as sbn
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [6]:
wine = pd.read_csv('winequality-red.csv') 
wine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [7]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

Kiểm tra số lượng NaN (not a number) trong data.

In [8]:
wine.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

Dữ liệu không bị thiếu giá trị nào!

## Get input, output from data

In [9]:
X = wine.drop(columns=['quality'])
y = wine['quality']

In [10]:
X

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [11]:
y = np.array(y)

In [12]:
features_X = X.columns
print(features_X)

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol'],
      dtype='object')

In [13]:
# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=11)

## Preprocessing

Dùng ```StandardScaler()``` để chuẩn hóa dữ liệu.

In [14]:
scalerX = StandardScaler()
X_train = scalerX.fit_transform(X_train)
X_test = scalerX.transform(X_test)

In [15]:
X_train

array([[ 0.6564853 ,  0.12682335,  1.98531668, ..., -0.90793828,
         0.09666965, -0.75581635],
       [-0.42532635, -0.7137413 ,  0.08605684, ...,  0.92679388,
        -0.39699076, -0.84869051],
       [-1.96263764, -0.60166601, -1.40255222, ...,  2.63047375,
         0.52862251,  3.33064649],
       ...,
       [-0.02676417,  1.80795266, -0.68391336, ...,  0.33705854,
        -0.70552851, -0.29144557],
       [-0.76695108,  0.91135036, -1.04323279, ...,  0.46811084,
        -0.33528321,  0.82304429],
       [-0.19757653, -0.26544015,  0.34271358, ..., -0.18715064,
         0.0349621 ,  1.84466   ]])

## Modeling

Ta lần lượt sử dụng các Model SVM, Logistic Regression và Decision Tree để train data và dự đoán kết quả. 

Để nhanh chóng, chúng ta sẽ dùng các model đã được sklearn build sẵn.

Chúng ta sử dụng hàm score cho cả 2 tập là Train và Test để đo accuracy score cho cả 2.

### SVM

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
svc = SVC()
svc.fit(X_train, y_train)

SVC()

In [17]:
print("Accuracy score của SVC cho tập test:",svc.score(X_test, y_test))
print("Accuracy score của SVC cho tập train:",svc.score(X_train, y_train))

Accuracy score của SVC cho tập test: 0.625
Accuracy score của SVC cho tập train: 0.6684539767649688

### Logistic Regression

In [18]:
LR = LogisticRegression(multi_class='ovr')
LR.fit(X_train, y_train)

LogisticRegression(multi_class='ovr')

In [19]:
print("Accuracy score của Logistic Regression cho tập test:",LR.score(X_test, y_test))
print("Accuracy score của Logistic Regression cho tập train:",LR.score(X_train, y_train))

Accuracy score của Logistic Regression cho tập test: 0.5979166666666667
Accuracy score của Logistic Regression cho tập train: 0.5960679177837355

### Decision Tree

In [20]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier()
DT.fit(X_train, y_train)

DecisionTreeClassifier()

In [21]:
print("Accuracy score của Decision Tree cho tập test:",DT.score(X_test, y_test))
print("Accuracy score của Decision Tree cho tập train:",DT.score(X_train, y_train))

Accuracy score của Decision Tree cho tập test: 0.6
Accuracy score của Decision Tree cho tập train: 1.0

# Ensemble

Ensemble Learning là một kỹ thuật trong Machine Learning mà trong đó nhiều mô hình (thường được gọi là "weak learners") được kết hợp lại với nhau để tạo ra một mô hình mạnh mẽ hơn, được gọi là "strong learner". Mục tiêu chính của Ensemble Learning là cải thiện độ chính xác của dự đoán và giúp mô hình có khả năng tổng quát hóa tốt trên dữ liệu mới.

Có ba phương pháp ensemble chính thường được sử dụng:
+ Bagging (Bootstrap Aggregating)
+ Boosting
+ Stacking

## Bagging method

**Bagging** dựa trên ý tưởng lấy mẫu có hoàn lại (bootstrap) từ tập dữ liệu huấn luyện để tạo ra nhiều tập dữ liệu con và sau đó huấn luyện cùng một loại model trên mỗi tập dữ liệu con này. Cuối cùng, kết quả từ tất cả các model này sẽ được tổng hợp lại (thông qua lấy trung bình hoặc bỏ phiếu) để tạo ra dự đoán cuối cùng.

In [22]:
from sklearn.ensemble import BaggingClassifier

### BaggingClassifier
**Các tham số của BaggingClassifier**:
+ estimator: mô hình muốn ensemble
+ n_estimator: số lượng mô hình cần được tạo trong quá trình bagging
+ random_state: cố định trạng thái random

In [23]:
bagg_model_dt = BaggingClassifier(estimator=DecisionTreeClassifier(), n_estimators=15, random_state=11)
bagg_model_dt.fit(X_train, y_train)
bagg_model_dt.score(X_test, y_test)

0.65625

In [24]:
bagg_model_svm = BaggingClassifier(estimator=SVC(), n_estimators=11, random_state=11)
bagg_model_svm.fit(X_train, y_train)
bagg_model_svm.score(X_test, y_test)

0.6458333333333334

In [25]:
bagg_model_svm = BaggingClassifier(estimator=LogisticRegression(max_iter=3000), n_estimators=15, random_state=11)
bagg_model_svm.fit(X_train, y_train)
bagg_model_svm.score(X_test, y_test)

0.60625

### RandomForest

Đối với ensemble của DecisionTree, Sklearn cung cấp 1 model gọi là **RandomForest**. Random Forest là một phiên bản cụ thể của Bagging sử dụng các cây quyết định làm mô hình cơ bản.

In [26]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(n_estimators=15, random_state=11)
rf_clf.fit(X_train, y_train)
rf_clf.score(X_test, y_test)

0.6625

## Boosting Method

**Boosting** là một nhóm các thuật toán mà ở đó các mô hình được huấn luyện tuần tự, với mỗi mô hình gắng sức để sửa lỗi của mô hình trước đó. Mỗi mô hình sau sẽ chú ý nhiều hơn tới những trường hợp mà mô hình trước đó đã dự đoán sai bằng cách tăng trọng số cho chúng. Cuối cùng, dự đoán từ tất cả các mô hình sẽ được tổng hợp lại để tạo ra dự đoán cuối cùng.

### Adaboost - Adaptive Boosting

**Các tham số của AdaBoostClassifier**:
+ estimator: mô hình muốn ensemble.
+ n_estimator: Số lượng mô hình học yếu (stumps) tối đa cần được tạo.
+ random_state: cố định trạng thái random.
+ learning_rate: Trọng số được áp dụng cho mỗi mô hình ở mỗi lần lặp, để kiểm soát tốc độ cập nhật trọng số của dữ liệu.

In [27]:
from sklearn.ensemble import AdaBoostClassifier

In [28]:
adaboost_svm = AdaBoostClassifier(DecisionTreeClassifier(), n_estimators=100, random_state=11)
adaboost_svm.fit(X_train, y_train)

adaboost_svm.score(X_test, y_test)

0.5895833333333333

### GradientBoosting

GradientBoosting là 1 phiên bản cụ thể của Boosting sử dụng cây quyết định làm mô hình cơ bản.

**Các tham số của GradientBoostingClassifier**:
+ n_estimators: Số lượng "rounds" boost. Mỗi round thêm một mô hình vào chuỗi.
+ random_state: cố định trạng thái random.
+ learning_rate: Trọng số được áp dụng cho mỗi mô hình ở mỗi lần lặp, để kiểm soát tốc độ cập nhật trọng số của dữ liệu.
+ các tham số khác tương tự như RandomForest.

In [29]:
# XGBoost: sử dụng gradient boosting.
# Mục tiêu: Tối ưu hóa cả hiệu suất model và tốc độ thực thi
from sklearn.ensemble import GradientBoostingClassifier

xgboost = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=11)
xgboost.fit(X_train, y_train)

xgboost.score(X_test, y_test)

0.6729166666666667

## Stacking Methods

Trong **Stacking**, nhiều mô hình (cơ bản) khác nhau được huấn luyện độc lập với nhau từ cùng một tập dữ liệu huấn luyện. Sau khi hoàn thành quá trình huấn luyện, một mô hình mới (gọi là meta-learner hoặc mô hình cấp cao) sẽ được huấn luyện dựa trên các dự đoán (chứ không phải dữ liệu ban đầu) của các mô hình cơ bản. Mô hình meta-learner này sẽ học cách kết hợp tốt nhất các dự đoán từ các mô hình cơ bản để đưa ra dự đoán cuối cùng.

**Các tham số của StackingClassifier**:
+ estimators: Danh sách các mô hình sơ cấp (base learners). Thường được cung cấp dưới dạng một danh sách tuple, mỗi tuple chứa tên (string) và instance của mô hình.
+ final_estimator: Mô hình thứ cấp (meta-learner) dùng để kết hợp dự đoán từ các mô hình sơ cấp. Nếu không được chỉ định, mặc định thường là LogisticRegression trong sklearn.

In [30]:
from sklearn.ensemble import StackingClassifier

estimators = [
  ('rf', DecisionTreeClassifier(min_samples_leaf= 5, max_features= None, max_depth= None, criterion= 'gini')),
  ('svr', SVC(random_state=11))]
final_estimator = LogisticRegression(max_iter=3000, C= 1, penalty= 'l2')
stacking = StackingClassifier(estimators, final_estimator)

stacking.fit(X_train, y_train)
stacking.score(X_test, y_test)

0.6104166666666667

Dựa vào accuracy score trên test, ta thấy rằng việc sử dụng ensemble mang lại kết quả tốt hơn so với việc chỉ sử dụng đơn lẻ 1 model.

# Hyperparameter-tuning

**Nhận xét**:
Khi sử dụng các mô hình học máy mà giữ nguyên các cài đặt mặc định:
+ Kết quả thu được thường không thể đạt được cao nhất.
+ Có nguy cơ dẫn đến **Overfitting** và **Underfitting** (Decision Tree đạt 100% cho tập train và chỉ 60% cho tập test, đây là dấu hiệu của overfitting).
+ Ngoài ra có thể dẫn đến tiêu tốn nhiều tài nguyên tính toán mà hiệu suất không cao.

**Hyperparameter-tuning** là quá trình tối ưu hóa một mô hình machine learning bằng cách điều chỉnh các *siêu tham số* (hyperparameter) để cải thiện hiệu suất của nó trên tập dữ liệu cụ thể. 

Trong hyperparameter-tuning, ta sẽ tìm các bộ siêu tham số tối ưu như: 
+ Learning rate trong gradient descent
+ Số lượng epochs
+ Kích thước batch
+ Tham số liên quan đến cấu trúc của mô hình
+ ...

**Hyperparameter tuning trong sklearn**: sklearn cũng cung cấp những kỹ thuật thông dụng trong fine-tuning, phổ biến nhất là Grid Search và Randomized Search.

## GridSearch

GridSearch là một kỹ thuật phổ biến trong việc tìm kiếm không gian của các hyperparameters với mục tiêu tìm bộ hyperparameters tốt nhất cho một mô hình học máy nhất định. 

Đây là một phương pháp brute-force, tức là nó thử mọi tổ hợp có thể của hyperparameters để tìm ra bộ tối ưu nhất dựa trên một tiêu chí đánh giá cụ thể.

**Cách hoạt động**:  
+ Truyền vào một tập các hyperparameters và các giá trị tiềm năng cho mỗi hyperparameter cần thử nghiệm.
+ Thử nghiệm tất cả tổ hợp.
+ Chọn Bộ Hyperparameters tốt nhất.

**Ưu điểm**: 
+ GridSearch đảm bảo rằng từng tổ hợp của các hyperparameters đều được thử nghiệm, giúp tìm ra bộ cấu hình tối ưu nhất.

**Nhược điểm**:
+ Tốn Kém Về Mặt Tính Toán (do brute-force).

**Tham số của GridSeach**:
+ estimator: mô hình muốn fine tune.
+ param_grid: một từ điển (dictionary) hoặc một danh sách các từ điển, với mỗi *key* là tên của hyperparameter và *value* là danh sách các giá trị mà bạn muốn thử nghiệm cho hyperparameter đó.
+ scoring: tiêu chí đánh giá mô hình ('accuracy', 'f1', 'precision', 'recall', ...).
+ cv: cross-validation.
+ verbose: mức độ chi tiết mà GridSearchCV sẽ in ra trong quá trình thực hiện (giá trị cao hơn nghĩa là thông báo nhiều hơn).

In [31]:
from sklearn.model_selection import GridSearchCV

### SVM

In [32]:
from sklearn.svm import SVC

svc=SVC() 

parameters = [ 
              {'C':[1, 10, 100], 'kernel':['linear']},
               {'C':[1, 10, 100], 'kernel':['rbf'], 'gamma':[0.8, 1, 1.2]},
            #    {'C':[1], 'kernel':['poly'], 'gamma':["scale"], 'degree':[2, 3, 4,5,6,7]}
            ]

svc_cv = GridSearchCV(estimator = svc,  
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5,
                           verbose=0)
svc_cv.fit(X_train, y_train)

print("Logistic Regression Parameters: {}".format(svc_cv.best_params_))
print("Best score is {}".format(svc_cv.best_score_))

Logistic Regression Parameters: {'C': 1, 'gamma': 1, 'kernel': 'rbf'}
Best score is 0.6532471172325433

### Logistic Regression

In [33]:
from sklearn.linear_model import LogisticRegression
 
c_space = np.logspace(-10, 10, 30)
param_grid = {'C': c_space, 
              "penalty": ["l2"],
              "max_iter": [5000],
              }
 
LR = LogisticRegression()
 
LR_cv = GridSearchCV(LR, param_grid, cv = 5)
 
LR_cv.fit(X_train, y_train)
 
print("Logistic Regression Parameters: {}".format(LR_cv.best_params_))
print("Best score is {}".format(LR_cv.best_score_))

Logistic Regression Parameters: {'C': 0.09236708571873885, 'max_iter': 5000, 'penalty': 'l2'}
Best score is 0.6004884689301729

### Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()

param_tree = {"max_depth": np.arange(1, 10),
              "max_features": list(range(3, 10)),
              "min_samples_leaf": list(range(5, 50,5)),
              "min_samples_split": list(range(2, 10,2)),
            }

tree_cv = GridSearchCV(tree, param_tree, cv=5)

tree_cv.fit(X_train, y_train)

print("Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

Decision Tree Parameters: {'max_depth': 7, 'max_features': 5, 'min_samples_leaf': 40, 'min_samples_split': 4}
Best score is 0.6130245035233824

In [35]:
svc = SVC(**svc_cv.best_params_)
svc.fit(X_train, y_train)
print("Accuracy score của SVC cho tập test:",svc.score(X_test, y_test))
print("Accuracy score của SVC cho tập train:",svc.score(X_train, y_train))
LR = LogisticRegression(**LR_cv.best_params_)
LR.fit(X_train, y_train)
print("Accuracy score của Logistic Regression cho tập test:",LR.score(X_test, y_test))
print("Accuracy score của Logistic Regression cho tập train:",LR.score(X_train, y_train))
DT = DecisionTreeClassifier(**tree_cv.best_params_)
DT.fit(X_train, y_train)
print("Accuracy score của Decision Tree cho tập test:",DT.score(X_test, y_test))
print("Accuracy score của Decision Tree cho tập train:",DT.score(X_train, y_train))

Accuracy score của SVC cho tập test: 0.6229166666666667
Accuracy score của SVC cho tập train: 0.9401251117068812
Accuracy score của Logistic Regression cho tập test: 0.6104166666666667
Accuracy score của Logistic Regression cho tập train: 0.6032171581769437
Accuracy score của Decision Tree cho tập test: 0.575
Accuracy score của Decision Tree cho tập train: 0.6398570151921358

Từ kết quả trên, ta có thể thấy rằng, kết quả sau khi sử dụng GridSearch tốt hơn so với model thông thường và cũng khắc phục overfitting.

## RandomizedSearchCV

RandomizedSearchCV là một kỹ thuật tối ưu hóa hyperparameters khác, giúp tìm kiếm không gian của các hyperparameters để tìm bộ hyperparameters tốt nhất cho một mô hình học máy. 

Khác với GridSearchCV, RandomizedSearchCV không thử hết tất cả các tổ hợp có thể mà thay vào đó chọn ngẫu nhiên một số tổ hợp để thử nghiệm.

**Cách hoạt động**:  
+ Truyền vào một tập các hyperparameters và các giá trị tiềm năng cho mỗi hyperparameter cần thử nghiệm.
+ Chọn ngẫu nhiên một số tổ hợp: Thay vì thử tất cả các tổ hợp, RandomizedSearchCV chọn ngẫu nhiên một số lượng tổ hợp hyperparameters xác định trước để thử nghiệm.
+ Chọn bộ Hyperparameters tốt nhất.

**Ưu điểm**: 
+ Hiệu Quả Hơn Về Mặt Tính Toán: Do chỉ thử nghiệm một số lượng tổ hợp ngẫu nhiên thay vì tất cả các tổ hợp có thể.

**Nhược điểm**:
+ Không Đảm Bảo Tìm Ra Bộ Tối Ưu Nhất: Vì chỉ thử nghiệm một số tổ hợp ngẫu nhiên nên có thể bỏ lỡ bộ cấu hình tối ưu nhất.

### SVM

In [36]:
from sklearn.model_selection import RandomizedSearchCV
from sklearn.svm import SVC

svc=SVC() 

parameters = [ {'C':[1, 10, 100], 'kernel':['linear']},
               {'C':[1, 10, 100], 'kernel':['rbf'], 'gamma':[0.8, 1, 1.2]},
            ]

grid_search = RandomizedSearchCV(svc, parameters, cv = 5)
grid_search.fit(X_train, y_train)

print("Tuned Logistic Regression Parameters: {}".format(grid_search.best_params_))
print("Best score is {}".format(grid_search.best_score_))

Tuned Logistic Regression Parameters: {'kernel': 'rbf', 'gamma': 1, 'C': 1}
Best score is 0.6532471172325433

### Logistic Regression

In [37]:
c_space = np.logspace(-10, 10, 30)
param_grid = {'C': c_space, 
              "penalty": ["l2"],
              "max_iter": [5000],
              }
 
LR = LogisticRegression()
 
LR_cv = RandomizedSearchCV(LR, param_grid, cv = 5)
 
LR_cv.fit(X_train, y_train)
 
print("Logistic Regression Parameters: {}".format(LR_cv.best_params_))
print("Best score is {}".format(LR_cv.best_score_))

Logistic Regression Parameters: {'penalty': 'l2', 'max_iter': 5000, 'C': 0.09236708571873885}
Best score is 0.6004884689301729

In [38]:
### Decision Tree

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import RandomizedSearchCV
 
param_dist = {"max_depth": np.arange(1, 15),
              "max_features": list(range(3, 15)),
              "min_samples_leaf": list(range(2, 50,1)),
              "min_samples_split": list(range(2, 50,1)),
            }

tree = DecisionTreeClassifier()
 
tree_cv = RandomizedSearchCV(tree, param_dist, cv = 5)
 
tree_cv.fit(X_train, y_train)
 
print("Decision Tree Parameters: {}".format(tree_cv.best_params_))
print("Best score is {}".format(tree_cv.best_score_))

Decision Tree Parameters: {'min_samples_split': 46, 'min_samples_leaf': 9, 'max_features': 7, 'max_depth': 11}
Best score is 0.5853619474695708

In [40]:
svc = SVC(**grid_search.best_params_)
svc.fit(X_train, y_train)
print("Accuracy score của SVC cho tập test:",svc.score(X_test, y_test))
print("Accuracy score của SVC cho tập train:",svc.score(X_train, y_train))
LR = LogisticRegression(**LR_cv.best_params_)
LR.fit(X_train, y_train)
print("Accuracy score của Logistic Regression cho tập test:",LR.score(X_test, y_test))
print("Accuracy score của Logistic Regression cho tập train:",LR.score(X_train, y_train))
DT = DecisionTreeClassifier(**tree_cv.best_params_)
DT.fit(X_train, y_train)
print("Accuracy score của Decision Tree cho tập test:",DT.score(X_test, y_test))
print("Accuracy score của Decision Tree cho tập train:",DT.score(X_train, y_train))

Accuracy score của SVC cho tập test: 0.6229166666666667
Accuracy score của SVC cho tập train: 0.9401251117068812
Accuracy score của Logistic Regression cho tập test: 0.6104166666666667
Accuracy score của Logistic Regression cho tập train: 0.6032171581769437
Accuracy score của Decision Tree cho tập test: 0.5833333333333334
Accuracy score của Decision Tree cho tập train: 0.7015192135835567

Ta thấy rằng, tốc độ thực thi của RandomizeSearchCV khá nhanh so với GridSearchCV, tuy nhiên, kết quả thì đôi khi không tốt như GridSearchCV.